### PR TITLE
Generate interfaces for new projects

### PR DESCRIPTION
**Pull request by cahz**
For many small BSV modules, writing the interface definitions and connecting it to the testbench is quite a lot of copy-paste effort. Therefore I had the idea to add it to the `bsvNew` script. 

The current version is not really advanced (it is actually quite hacky) but fits my intended use-case.

### CODE REVIEW

**Comment by jahofmann** [comment]
Thanks for the contribution, looks good.

Could you add some help text describing the supported interfaces? Right now a user needs to look into the code to figure out what works.

**Comment by cahz** [comment]
Good point, I have added the list of interfaces to the help text.

**Comment by jahofmann** [comment]
Thank you for incorporating that change.

Another issue I've encountered is that when multiple interfaces of the same type are added, they all share the same name and test bench BRAM etc.

**Comment by cahz** [comment]
Yes, specifying an interface multiple times causes issues. Probably I will add some kind of enumeration.

**Comment by cahz** [comment]
Added the enumeration and also AXI lite master for completeness

**Comment by jahofmann** [comment]
Looks good, thanks!

**Pull request merged**
